jobs:
  sync-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout guimox-web repository
        uses: actions/checkout@v4

      - name: Download blog posts
        run: |
          mkdir -p src/content/posts
          cd src/content/posts

          # Clone the guimox-posts repository and checkout the main branch
          git clone --depth 1 https://github.com/guimox/guimox-posts.git temp-repo
          cp temp-repo/*.md .
          rm -rf temp-repo

      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git add src/content/posts
          git commit -m "chore: update blog posts automatically"
          git push https://x-access-token:${{ secrets.PAT_GITHUB }}@github.com/guimox/guimox-web.git HEAD:main
