name: Sync Blog Posts

on:
  repository_dispatch:
    types: [sync-posts]
  workflow_dispatch:
  schedule:
    - cron: '50 18 * * *'

jobs:
  sync-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout guimox-web repository
        uses: actions/checkout@v4

      - name: Download blog posts
        run: |
          mkdir -p src/content/posts
          cd src/content/posts

          # Download all .md files from the guimox-posts repository
          wget -r -np -nH -R "index.html*" -A "*.md" \
              https://raw.githubusercontent.com/guimox/guimox-posts/main/

      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git add src/content/posts
          git commit -m "chore: update blog posts automatically"
          git push
